!include ../../../styles/PlantUML_StyleSheet.puml

actor 사용자 as user #9EA0CA
participant "Clova 앱" as ca #9EA0CA
participant "클라이언트 기기" as cli #9EA0CA
participant CIC as cic #05D686

group 설정 정보 동기화
  user ->> ca: 기기 현재 설정 정보 조회
  activate ca
  ca ->> cic: 기기 현재 설정 정보 동기화 요청
  activate cic

    cic ->> cli: Settings.ExpectReport 지시 메시지 전송
    activate cli
    cli ->> cic: Settings.Report 이벤트 메시지 전송
    deactivate cli

  cic ->> ca: 기기 현재 설정 정보 동기화 지시
  deactivate cic
  ca -> ca: 기기 설정 정보 갱신
  ca ->> user: 기기 설정 정보 제공
  deactivate ca
end

group Clova 앱을 통한 설정 변경
  user ->> ca: 기기 설정 변경
  activate ca
  ca ->> cic: 기기 설정 변경 요청
  activate cic

    cic ->> cli: Settings.Update 지시 메시지 전송
    activate cli
    cli ->> cic: Settings.Report 이벤트 메시지 전송
    deactivate cli

  cic ->> ca: 변경된 설정 정보로 동기화 지시
  deactivate cic
  ca -> ca: 기기 설정 정보 갱신
  ca ->> user: 기기 설정 정보 제공
  deactivate ca
end

group 기기 자체 설정 변경
  user ->> cli: 기기 설정 변경
  activate cli
      cli ->> cic: Settings.Report 이벤트 메시지 전송
  deactivate cli
      activate cic

  cic ->> ca: 변경된 설정 정보로 동기화 지시
  deactivate cli
  activate ca
  deactivate cic
  ca -> ca: 기기 설정 정보 갱신
  ca ->> user: 기기 설정 정보 제공
  deactivate ca
end
